@startuml
class CreateTradeCommand {
    + CreateTradeCommand(userManager:IUserManager, userRequestTrade:UserRequestTrade)
    + <<override>> Execute() : Response
}
ProtectedRouteCommand <|-- CreateTradeCommand
@enduml
