@startuml
class DeleteTradeCommand {
    + DeleteTradeCommand(userManager:IUserManager, tradeId:string)
    + <<override>> Execute() : Response
}
ProtectedRouteCommand <|-- DeleteTradeCommand
@enduml
