@startuml
class UserManager {
    + UserManager(userRepository:IUserRepository)
    + LoginUser(credentials:Credentials) : User
    + GetUser(username:string) : User
    + GetUserData(username:string) : UserData
    + EditUserData(username:string, userData:UserData) : void
    + GetScores() : List<Score>
    + GetStack(username:string) : Stack
    + GetDeck(username:string) : Deck
    + SetDeck(username:string, ids:List<string>) : bool
    + AddPackage(package:List<UserRequestCard>) : bool
    + GetUserStats(username:string) : Stats
    + RegisterUser(credentials:Credentials) : void
    + AquirePackage(username:string) : bool
    + CreateTrade(username:string, userRequestTrade:UserRequestTrade) : bool
    + ListTrades() : List<ReadableTrade>
    + AcceptTrade(username:string, tradeId:string, cardId:string) : bool
    + DeleteTrade(username:string, tradeId:string) : bool
    + LogoutUser(token:string) : bool
}
IUserManager <|-- UserManager
@enduml
