@startuml
!include ./MonsterTradingCardsGameServer.Test/FireRuleTest.puml
!include ./MonsterTradingCardsGameServer.Test/WaterRuleTest.puml
!include ./MonsterTradingCardsGameServer.Test/NormalRuleTest.puml
!include ./MonsterTradingCardsGameServer/Program.puml
!include ./MonsterTradingCardsGameServer.Core/Listener/HttpListener.puml
!include ./MonsterTradingCardsGameServer.Core/Listener/IListener.puml
!include ./MonsterTradingCardsGameServer.Core/Response/Response.puml
!include ./MonsterTradingCardsGameServer.Core/Response/StatusCode.puml
!include ./MonsterTradingCardsGameServer.Core/Server/HttpServer.puml
!include ./MonsterTradingCardsGameServer.Core/Server/IServer.puml
!include ./MonsterTradingCardsGameServer.Core/Request/RequestContext.puml
!include ./MonsterTradingCardsGameServer.Core/Request/HttpMethod.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/IRouteCommandExecutor.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/IRouteCommand.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/IProtectedRouteCommand.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/Router.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/RouteNotAuthorizedException.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/IRouter.puml
!include ./MonsterTradingCardsGameServer.Core/Routing/IRouteParser.puml
!include ./MonsterTradingCardsGameServer.Core/Authentication/IIdentityProvider.puml
!include ./MonsterTradingCardsGameServer.Core/Authentication/IIdentity.puml
!include ./MonsterTradingCardsGameServer.Core/Client/IClient.puml
!include ./MonsterTradingCardsGameServer.Core/Client/HttpClient.puml
!include ./MonsterTradingCardsGameServer/Trades/UniversalTrade.puml
!include ./MonsterTradingCardsGameServer/Trades/ReadableTrade.puml
!include ./MonsterTradingCardsGameServer/Trades/UserRequestTrade.puml
!include ./MonsterTradingCardsGameServer/Cards/MonsterType.puml
!include ./MonsterTradingCardsGameServer/Cards/ReadableCard.puml
!include ./MonsterTradingCardsGameServer/Cards/Package.puml
!include ./MonsterTradingCardsGameServer/Cards/Spell.puml
!include ./MonsterTradingCardsGameServer/Cards/Deck.puml
!include ./MonsterTradingCardsGameServer/Cards/Modification.puml
!include ./MonsterTradingCardsGameServer/Cards/UniversalCard.puml
!include ./MonsterTradingCardsGameServer/Cards/CardNotFoundException.puml
!include ./MonsterTradingCardsGameServer/Cards/Card.puml
!include ./MonsterTradingCardsGameServer/Cards/TooFewCoinsException.puml
!include ./MonsterTradingCardsGameServer/Cards/UserRequestCard.puml
!include ./MonsterTradingCardsGameServer/Cards/Stack.puml
!include ./MonsterTradingCardsGameServer/Cards/CardCollection.puml
!include ./MonsterTradingCardsGameServer/Cards/Monster.puml
!include ./MonsterTradingCardsGameServer/Users/UserIdentityProvider.puml
!include ./MonsterTradingCardsGameServer/Users/PasswordManager.puml
!include ./MonsterTradingCardsGameServer/Users/UserNotFoundException.puml
!include ./MonsterTradingCardsGameServer/Users/IUserManager.puml
!include ./MonsterTradingCardsGameServer/Users/User.puml
!include ./MonsterTradingCardsGameServer/Users/Credentials.puml
!include ./MonsterTradingCardsGameServer/Users/SimpleUser.puml
!include ./MonsterTradingCardsGameServer/Users/DuplicateUserException.puml
!include ./MonsterTradingCardsGameServer/Users/Score.puml
!include ./MonsterTradingCardsGameServer/Users/UserManager.puml
!include ./MonsterTradingCardsGameServer/Users/ISimpleUser.puml
!include ./MonsterTradingCardsGameServer/Users/Stats.puml
!include ./MonsterTradingCardsGameServer/Users/UserData.puml
!include ./MonsterTradingCardsGameServer/Battles/BattleNotFoundException.puml
!include ./MonsterTradingCardsGameServer/Battles/BattleStatus.puml
!include ./MonsterTradingCardsGameServer/Battles/BattleFailedException.puml
!include ./MonsterTradingCardsGameServer/Battles/IBattleManager.puml
!include ./MonsterTradingCardsGameServer/Battles/BattleResult.puml
!include ./MonsterTradingCardsGameServer/Battles/BattleManager.puml
!include ./MonsterTradingCardsGameServer/Battles/Battle.puml
!include ./MonsterTradingCardsGameServer/Battles/Round.puml
!include ./MonsterTradingCardsGameServer/Battles/InvalidDeckException.puml
!include ./MonsterTradingCardsGameServer/Rules/DragonFireElveRule.puml
!include ./MonsterTradingCardsGameServer/Rules/OrgWizardRule.puml
!include ./MonsterTradingCardsGameServer/Rules/FireRule.puml
!include ./MonsterTradingCardsGameServer/Rules/NoSuchRuleException.puml
!include ./MonsterTradingCardsGameServer/Rules/KrakenSpellRule.puml
!include ./MonsterTradingCardsGameServer/Rules/GoblinDragonRule.puml
!include ./MonsterTradingCardsGameServer/Rules/KnightWaterRule.puml
!include ./MonsterTradingCardsGameServer/Rules/NormalRule.puml
!include ./MonsterTradingCardsGameServer/Rules/Rule.puml
!include ./MonsterTradingCardsGameServer/Rules/WaterRule.puml
!include ./MonsterTradingCardsGameServer/Routing/MtcgDbSetup.puml
!include ./MonsterTradingCardsGameServer/Routing/AppendixRouteParser.puml
!include ./MonsterTradingCardsGameServer/Routing/Routes.puml
!include ./MonsterTradingCardsGameServer/DAL/IBattleRepository.puml
!include ./MonsterTradingCardsGameServer/DAL/InDatabaseUserRepository.puml
!include ./MonsterTradingCardsGameServer/DAL/InDatabaseBattleRepository.puml
!include ./MonsterTradingCardsGameServer/DAL/DatabaseData.puml
!include ./MonsterTradingCardsGameServer/DAL/IUserRepository.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/ProtectedRouteCommand.puml
!include ./MonsterTradingCardsGameServer.Core/obj/Debug/net5.0/MonsterTradingCardsGameServer.Core.AssemblyInfo.puml
!include ./MonsterTradingCardsGameServer.Core/obj/Debug/net5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include ./MonsterTradingCardsGameServer.Test/obj/Debug/net5.0/MonsterTradingCardsGameServer.Test.AssemblyInfo.puml
!include ./MonsterTradingCardsGameServer.Test/obj/Debug/net5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include ./MonsterTradingCardsGameServer/obj/Debug/net5.0/MonsterTradingCardsGameServer.AssemblyInfo.puml
!include ./MonsterTradingCardsGameServer/obj/Debug/net5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Trades/DeleteTradeCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Trades/CreateTradeCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Trades/AcceptTradeCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Trades/ListTradesCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Cards/GetDeckCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Cards/SetDeckCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Cards/GetStackCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Cards/AquirePackageCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Admin/AddPackageCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/LoginCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/ListBioCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/GetScoreBoardCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/LogoutUserCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/RegisterCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/EditBioCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Users/GetStatsCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Battles/StartBattleCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Battles/GetBattleCommand.puml
!include ./MonsterTradingCardsGameServer/Routing/RouteCommands/Battles/ListBattlesCommand.puml
@enduml
