@startuml
abstract class ProtectedRouteCommand {
    + {abstract} Execute() : Response
}
IProtectedRouteCommand <|-- ProtectedRouteCommand
ProtectedRouteCommand --> "User" User
ProtectedRouteCommand --> "Identity" IIdentity
@enduml
