@startuml
class BattleNotFoundException {
    + BattleNotFoundException()
    + BattleNotFoundException(message:string)
    + BattleNotFoundException(message:string, innerException:Exception)
}
Exception <|-- BattleNotFoundException
@enduml
