@startuml
class InvalidDeckException {
    + InvalidDeckException()
    + InvalidDeckException(message:string)
    + InvalidDeckException(message:string, innerException:Exception)
}
Exception <|-- InvalidDeckException
@enduml
